name: CD - Deploy to ECS

on:
  workflow_dispatch: {}             # run manually
  push:
    tags:
      - 'v*.*.*'                    # run on version tags like v0.1.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write               # if you switch to OIDC later
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Optional: ensure image exists (pull by tag if you use tags)
      - name: Show image to deploy
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          REPO: ${{ secrets.ECR_REPOSITORY }}
        run: |
          echo "Deploying image: $REGISTRY/$REPO:latest"

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster  "${{ secrets.ECS_CLUSTER }}" \
            --service  "${{ secrets.ECS_SERVICE }}" \
            --force-new-deployment \
            --region   "${{ secrets.AWS_REGION }}"
